import { Injectable } from '@angular/core';
import { RentalCar } from '../models/rental-car.service';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  
  getRentalCars(): RentalCar[] {
    return [
      {
        _id: '1',
        make: 'Dacia',
        model: 'Logan',
        year: 2022,
        category: 'Sedan',
        price: 250,
        priceUnit: 'day',
        images: ['/assets/images/cars/dacia-logan.jpg'],
        features: ['Climatisation', 'Radio', 'Bluetooth', 'USB'],
        transmission: 'manual',
        fuelType: 'Essence',
        seats: 5,
        available: true,
        location: 'Casablanca',
        description: 'Voiture économique idéale pour les déplacements en ville et sur route.',
        rating: 4.2,
        reviewCount: 18
      },
      {
        _id: '2',
        make: 'Renault',
        model: 'Clio',
        year: 2021,
        category: 'Compact',
        price: 220,
        priceUnit: 'day',
        images: ['/assets/images/cars/renault-clio.jpg'],
        features: ['Climatisation', 'Radio', 'Bluetooth', 'USB', 'GPS'],
        transmission: 'manual',
        fuelType: 'Diesel',
        seats: 5,
        available: true,
        location: 'Rabat',
        description: 'Compacte et économique, parfaite pour la ville.',
        rating: 4.5,
        reviewCount: 24
      },
      {
        _id: '3',
        make: 'Volkswagen',
        model: 'Tiguan',
        year: 2023,
        category: 'SUV',
        price: 450,
        priceUnit: 'day',
        images: ['/assets/images/cars/vw-tiguan.jpg'],
        features: ['Climatisation', 'Caméra de recul', 'GPS', 'Bluetooth', 'Sièges chauffants'],
        transmission: 'automatic',
        fuelType: 'Diesel',
        seats: 5,
        available: true,
        location: 'Marrakech',
        description: 'SUV spacieux et confortable pour vos voyages en famille.',
        rating: 4.8,
        reviewCount: 32
      },
      {
        _id: '4',
        make: 'Mercedes-Benz',
        model: 'Classe C',
        year: 2022,
        category: 'Luxury',
        price: 700,
        priceUnit: 'day',
        images: ['/assets/images/cars/mercedes-c.jpg'],
        features: ['Climatisation', 'Cuir', 'GPS', 'Bluetooth', 'Sièges chauffants', 'Toit ouvrant'],
        transmission: 'automatic',
        fuelType: 'Essence',
        seats: 5,
        available: true,
        location: 'Casablanca',
        description: 'Berline de luxe pour un confort optimal et une conduite agréable.',
        rating: 4.9,
        reviewCount: 15
      },
      {
        _id: '5',
        make: 'Toyota',
        model: 'Hilux',
        year: 2021,
        category: 'Truck',
        price: 500,
        priceUnit: 'day',
        images: ['/assets/images/cars/toyota-hilux.jpg'],
        features: ['Climatisation', '4x4', 'Bluetooth', 'Benne'],
        transmission: 'manual',
        fuelType: 'Diesel',
        seats: 5,
        available: true,
        location: 'Agadir',
        description: 'Pick-up robuste pour vos aventures tout-terrain et vos besoins professionnels.',
        rating: 4.6,
        reviewCount: 22
      },
      {
        _id: '6',
        make: 'Hyundai',
        model: 'H1',
        year: 2020,
        category: 'Van',
        price: 550,
        priceUnit: 'day',
        images: ['/assets/images/cars/hyundai-h1.jpg'],
        features: ['Climatisation', 'Radio', 'Bluetooth', '9 places'],
        transmission: 'manual',
        fuelType: 'Diesel',
        seats: 9,
        available: true,
        location: 'Tanger',
        description: 'Minibus spacieux idéal pour les groupes et les familles nombreuses.',
        rating: 4.3,
        reviewCount: 17
      },
      {
        _id: '7',
        make: 'Fiat',
        model: '500',
        year: 2022,
        category: 'Compact',
        price: 200,
        priceUnit: 'day',
        images: ['/assets/images/cars/fiat-500.jpg'],
        features: ['Climatisation', 'Radio', 'Bluetooth', 'USB'],
        transmission: 'manual',
        fuelType: 'Essence',
        seats: 4,
        available: true,
        location: 'Marrakech',
        description: 'Citadine compacte et élégante, parfaite pour explorer la ville.',
        rating: 4.4,
        reviewCount: 28
      },
      {
        _id: '8',
        make: 'BMW',
        model: 'X5',
        year: 2023,
        category: 'Luxury',
        price: 800,
        priceUnit: 'day',
        images: ['/assets/images/cars/bmw-x5.jpg'],
        features: ['Climatisation', 'Cuir', 'GPS', 'Bluetooth', 'Sièges chauffants', 'Toit panoramique'],
        transmission: 'automatic',
        fuelType: 'Diesel',
        seats: 5,
        available: true,
        location: 'Casablanca',
        description: 'SUV de luxe offrant performance et confort pour vos déplacements.',
        rating: 4.9,
        reviewCount: 12
      },
      {
        _id: '9',
        make: 'Peugeot',
        model: '208',
        year: 2021,
        category: 'Compact',
        price: 230,
        priceUnit: 'day',
        images: ['/assets/images/cars/peugeot-208.jpg'],
        features: ['Climatisation', 'Radio', 'Bluetooth', 'USB', 'Écran tactile'],
        transmission: 'manual',
        fuelType: 'Essence',
        seats: 5,
        available: false,
        location: 'Rabat',
        description: 'Citadine moderne et économique avec un design attrayant.',
        rating: 4.5,
        reviewCount: 20
      },
      {
        _id: '10',
        make: 'Audi',
        model: 'A4',
        year: 2022,
        category: 'Luxury',
        price: 650,
        priceUnit: 'day',
        images: ['/assets/images/cars/audi-a4.jpg'],
        features: ['Climatisation', 'Cuir', 'GPS', 'Bluetooth', 'Sièges chauffants'],
        transmission: 'automatic',
        fuelType: 'Diesel',
        seats: 5,
        available: true,
        location: 'Tanger',
        description: 'Berline premium alliant élégance, technologie et performance.',
        rating: 4.7,
        reviewCount: 14
      },
      {
        _id: '11',
        make: 'Ford',
        model: 'Transit',
        year: 2020,
        category: 'Van',
        price: 500,
        priceUnit: 'day',
        images: ['/assets/images/cars/ford-transit.jpg'],
        features: ['Climatisation', 'Radio', 'Bluetooth', '9 places'],
        transmission: 'manual',
        fuelType: 'Diesel',
        seats: 9,
        available: true,
        location: 'Agadir',
        description: 'Fourgon spacieux pour le transport de groupes ou de marchandises.',
        rating: 4.2,
        reviewCount: 9
      },
      {
        _id: '12',
        make: 'Kia',
        model: 'Sportage',
        year: 2021,
        category: 'SUV',
        price: 400,
        priceUnit: 'day',
        images: ['/assets/images/cars/kia-sportage.jpg'],
        features: ['Climatisation', 'Caméra de recul', 'Bluetooth', 'USB', 'Écran tactile'],
        transmission: 'automatic',
        fuelType: 'Diesel',
        seats: 5,
        available: true,
        location: 'Casablanca',
        description: 'SUV compact offrant un excellent rapport qualité-prix et un confort optimal.',
        rating: 4.6,
        reviewCount: 25
      }
    ];
  }
}